# Generated by Django 2.1 on 2020-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.BooleanField(default=True)),
                ('disc', models.TextField(max_length=1200)),
            ],
        ),
    ]
