# Generated by Django 2.1 on 2020-03-28 20:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200327_2157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name='areainfo',
            table='area',
        ),
    ]
